
development:
  adapter: postgresql
  encoding: unicode
  database: newsreader_app_development
  pool: 5
  host: localhost
  username: charlieg
  password:

  production:
  adapter: postgresql
  encoding: unicode
  database: newsreader_app_production
  pool: 5
  password:

